config/routes.rb
Rails.application.routes.draw do

  resources :news
  resources :news
  resources :playlist_users
  get 'friend/index'

  get 'friend/:id' => 'friend#show'

  resources :follows
  get 'usuarios/show'

  get 'usuarios/index'

  resources :playlist_contents
  resources :playlists
  get 'mymusic/show'

  get 'mymusic/index'

  resources :song_users
  get 'searcher/show'

  get 'searcher/index'

  get 'admin/show'

  get 'admin/index'

  resources :genders
  root 'welcome#show'
  get 'welcome/show'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do 
    get 'users/registrations/baneo' => 'users/registrations#baneo', :as => :baneo
    get 'users/registrations/desbaneo' => 'users/registrations#desbaneo', :as => :desbaneo
  end
 
  resources :songs
  resources :albums
  resources :artists

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :songs
	belongs_to :artist
	has_attached_file :image, styles: {medium: "400x300>", thumb: "100x100>" }, default_url: "/images/:style/misiing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs
	has_many :albums
end

app/models/follow.rb
class Follow < ActiveRecord::Base
end

app/models/gender.rb
class Gender < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
end

app/models/playlist_user.rb
class PlaylistUser < ActiveRecord::Base
	has_one :user
	has_one :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
	has_many :artists
	belongs_to :album
	belongs_to :artist
end

app/models/song_user.rb
class SongUser < ActiveRecord::Base
end

app/controllers/song_users_controller.rb
class SongUsersController < ApplicationController
  before_action :set_song_user, only: [:show, :edit, :update, :destroy]

  # GET /song_users
  # GET /song_users.json
  def index
    @song_users = SongUser.all
    @my_music = @song_users.select(:song_id).where("user_id = ?", current_user.id.to_s).distinct
    @artists = Artist.all
    @albums = Album.all
    @songs = Song.all
    @playlists_user = PlaylistUser.where("user_id=?",current_user)
    @playlists = Playlist.all
  end

  # GET /song_users/1
  # GET /song_users/1.json
  def show
    redirect_to song_users_url
  end

  # GET /song_users/new
  def new
    @song_user = SongUser.new
    create
  end

  # GET /song_users/1/edit
  def edit
  end

  # POST /song_users
  # POST /song_users.json
  def create
    @song_user = SongUser.new(song_user_params)

    respond_to do |format|
      if @song_user.save
        format.html { redirect_to @song_user}
        format.json { render :index, status: :created, location: @song_user }
      else
        format.html { render :new }
        format.json { render json: @song_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /song_users/1
  # PATCH/PUT /song_users/1.json
  def update
    respond_to do |format|
      if @song_user.update(song_user_params)
        format.html { redirect_to @song_user}
        format.json { render :show, status: :ok, location: @song_user }
      else
        format.html { render :edit }
        format.json { render json: @song_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /song_users/1
  # DELETE /song_users/1.json
  def destroy
    @song_user.destroy
    respond_to do |format|
      format.html { redirect_to song_users_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song_user
      @song_user = SongUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_user_params
      params.permit(:song_id, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/mymusic_helper.rb
module MymusicHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/song_users_helper.rb
module SongUsersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/song_users/_form.html.erb
<%= form_for(@song_user) do |f| %>
  <% if @song_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song_user.errors.count, "error") %> prohibited this song_user from being saved:</h2>

      <ul>
      <% @song_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song_id %><br>
    <%= f.number_field :song_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/song_users/edit.html.erb
<h1>Editing Song User</h1>

<%= render 'form' %>

<%= link_to 'Show', @song_user %> |
<%= link_to 'Back', song_users_path %>

app/views/song_users/index.html.erb
<html>
<head>
</head>
<body>
<div class="container" style="margin-left:20em;">
  <div class="row">
    <div class="col-md-10">
      <h1 class="my-4"><i class="fa fa-headphones"></i>  Mi Musica</h1>
    </div>
  </div>

  <% @my_music.each do |song| %>
    <% @my_song = @songs.find_by_id(song.song_id)%>
    <div class="row">
      <div class="col-md-2">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src=<%=@albums.find_by_id(@my_song.album_id).image.url(:medium) %> alt="">
        </a>
      </div>
      <div class="col-md-8">
        <h2><%= @my_song.name %></h2>
        <h5><%= @artists.find_by_id(@my_song.artist_id).name %></h5>
      </div>
      <div class="col-md-1">
        <a href="/songs/<%= @my_song.id %>">
          <button class="btn btn-info fa fa-play"></button>
        </a>
      </div>
      <div class="col-md-1">
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle fa fa-list" type="button" data-toggle="dropdown">
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <% @playlists_user.each do |playlist| %>
              <% playlist = @playlists.find_by_id(playlist.playlist_id) %>
              <li>
                <%= link_to new_playlist_content_path({:playlist_id => playlist.id, :song_id => @my_song.id}) do %>
                  <span class="fa fa-plus"><%= playlist.name %></span>
                <% end %>
              </li>
       
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>
</body>
</html>

app/views/song_users/new.html.erb
<h1>New Song User</h1>

<%= render 'form' %>

<%= link_to 'Back', song_users_path %>

app/views/song_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song:</strong>
  <%= @song_user.song_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @song_user.user_id %>
</p>

<%= link_to 'Edit', edit_song_user_path(@song_user) %> |
<%= link_to 'Back', song_users_path %>