config/routes.rb
Rails.application.routes.draw do

  resources :news
  resources :news
  resources :playlist_users
  get 'friend/index'

  get 'friend/:id' => 'friend#show'

  resources :follows
  get 'usuarios/show'

  get 'usuarios/index'

  resources :playlist_contents
  resources :playlists
  get 'mymusic/show'

  get 'mymusic/index'

  resources :song_users
  get 'searcher/show'

  get 'searcher/index'

  get 'admin/show'

  get 'admin/index'

  resources :genders
  root 'welcome#show'
  get 'welcome/show'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do 
    get 'users/registrations/baneo' => 'users/registrations#baneo', :as => :baneo
    get 'users/registrations/desbaneo' => 'users/registrations#desbaneo', :as => :desbaneo
  end
 
  resources :songs
  resources :albums
  resources :artists

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :songs
	belongs_to :artist
	has_attached_file :image, styles: {medium: "400x300>", thumb: "100x100>" }, default_url: "/images/:style/misiing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs
	has_many :albums
end

app/models/follow.rb
class Follow < ActiveRecord::Base
end

app/models/gender.rb
class Gender < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
end

app/models/playlist_user.rb
class PlaylistUser < ActiveRecord::Base
	has_one :user
	has_one :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
	has_many :artists
	belongs_to :album
	belongs_to :artist
end

app/models/song_user.rb
class SongUser < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
    @users = User.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    parametros = news_params
    parametros = parametros.merge({:user_id => current_user.id})
    @news = News.new(parametros)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :description)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/mymusic_helper.rb
module MymusicHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/searcher_helper.rb
module SearcherHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/news/_form.html.erb
<boby style="background-color: #ccc;">
  <class class="bg-silver">
    <div class="row" style="margin-top:10em;">
      <%= form_for(@news, :html => {:class => 'col-sm-3 col-sm-offset-4 well'}) do |f| %>
        <% if @news.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

            <ul>
            <% @news.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <h1 align="center">Noticia</h1>
        <div class="row" style="margin-button: 2em;">
          <div class="col-sm-4 col-sm-offset-4"">
            <p class="text-center "style="width: 7em; height: 7em; border-radius: 100%; background-color: white; margin: 0 auto; padding-top:2em;">
              <span style="font-size: 3em; color: #597BB8;" class="fa fa-newspaper-o"></span>
            </p>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :title %><br>
            <%= f.text_field :title, class: 'form-control', :required => true %>
          </div>
          <div class="form-group">
            <%= f.label :description %><br>
            <%= f.text_area :description, class: 'form-control', :required => true %>
          </div>
          <div class="row">
            <div class="actions">
              <%= f.submit %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </class>
</body>
<script>
var btnCust = '<button type="button" class="btn btn-secondary" title="Add picture tags" ' + 
    'onclick="alert(\'Call your custom code here.\')">' +
    '<i class="glyphicon glyphicon-tag"></i>' +
    '</button>'; 
</script>

app/views/news/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .button {
    display: inline-block;
    border-radius: 4px;
    background-color: #3ADF00;
    border: none;
    color: #FFFFFF;
    text-align: center;
    font-size: 28px;
    padding: 10px;
    width: 200px;
    transition: all 0.5s;
    cursor: pointer;
    margin: 5px;
  }

  .button span {
    cursor: pointer;
    display: inline-block;
    position: relative;
    transition: 0.5s;
  }

  .button span:after {
    content: '\00bb';
    position: absolute;
    opacity: 0;
    top: 0;
    right: -20px;
    transition: 0.5s;
  }

  .button:hover span {
    padding-right: 25px;
  }

  .button:hover span:after {
    opacity: 1;
    right: 0;
  }
  </style>
</head>
<body>
<div class="container" style="margin-left:20em;">
  <div class="row">
    <div class="col-md-10">
      <h1 class="my-4"><i class="fa fa-newspaper-o"></i>  Noticias</h1>
    </div>
    <div class="col-md-2">
      <%= link_to new_news_path, class: 'button btn-success btn-xs', title: 'New Artist' do %>
        <span class="fa fa-plus">  Agregar</span>
      <% end %>
    </div>
  </div>

  <% @news.each do |news| %>
    <% user = @users.find_by_id(news.user_id) %>
    <div class="row">
      <div class="col-md-2">
        <img class="img-fluid rounded mb-3 mb-md-0" src= <%= user.image.url(:medium) %> alt="">
        <h4 align="center"><%= (user.email) %></h4>

      </div>
      <div class="col-md-4">
        <h2><%= news.title %></h2>
        <h4>(<%= (news.created_at.strftime("%d %b. %Y")) %>)</h4>
        <p><%= news.description%></p>
      </div>
    <hr>
  <% end %>
</div>
</body>
</html>

app/views/news/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @news.description %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>