config/routes.rb
Rails.application.routes.draw do

  resources :news
  resources :news
  resources :playlist_users
  get 'friend/index'

  get 'friend/:id' => 'friend#show'

  resources :follows
  get 'usuarios/show'

  get 'usuarios/index'

  resources :playlist_contents
  resources :playlists
  get 'mymusic/show'

  get 'mymusic/index'

  resources :song_users
  get 'searcher/show'

  get 'searcher/index'

  get 'admin/show'

  get 'admin/index'

  resources :genders
  root 'welcome#show'
  get 'welcome/show'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do 
    get 'users/registrations/baneo' => 'users/registrations#baneo', :as => :baneo
    get 'users/registrations/desbaneo' => 'users/registrations#desbaneo', :as => :desbaneo
  end
 
  resources :songs
  resources :albums
  resources :artists

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :songs
	belongs_to :artist
	has_attached_file :image, styles: {medium: "400x300>", thumb: "100x100>" }, default_url: "/images/:style/misiing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs
	has_many :albums
end

app/models/follow.rb
class Follow < ActiveRecord::Base
end

app/models/gender.rb
class Gender < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
end

app/models/playlist_user.rb
class PlaylistUser < ActiveRecord::Base
	has_one :user
	has_one :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
	has_many :artists
	belongs_to :album
	belongs_to :artist
end

app/models/song_user.rb
class SongUser < ActiveRecord::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
    @artists = Artist.all
    @albums = Album.all
    @playlists_user = PlaylistUser.where("user_id=?",current_user)
    @playlists = Playlist.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @album = Album.find_by_id(@song.album_id)
    @artist = Artist.find_by_id(@song.artist_id)
  end

  # GET /songs/new
  def new
    @song = Song.new
    @genders = Gender.all
    @artists = Artist.all
    @albums = Album.all
  end

  # GET /songs/1/edit
  def edit
    @artists = Artist.all
    @albums = Album.all
    @genders = Gender.all
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song}
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song}
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :year, :artist_id, :album_id, :gender_id, :duration, :punctuation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/mymusic_helper.rb
module MymusicHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/searcher_helper.rb
module SearcherHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/songs/_form.html.erb
<body class="bg-silver">
  <div class="row" style="margin-left:25em;">
    <%= form_for(@song, :html => {:class => 'col-sm-3 col-sm-offset-4 well'}) do |f| %>
      <% if @song.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

          <ul>
          <% @song.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <h1 align="center">Cancion</h1>
      <div class="row" style="margin-button: 2em;">
        <div class="col-sm-4 col-sm-offset-4">
          <p class="text-center "style="width: 7em; height: 7em; border-radius: 100%; background-color: white; margin: 0 auto; padding-top:2em;">
            <span style="font-size: 3em; color: #597BB8;" class="fa fa-music"></span>
          </p>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control', :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :year %><br>
          <%= f.number_field :year, class:"form-control", :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :artist_id %><br>
          <%= f.select(:artist_id, 
            options_for_select(
              @artists.select(:name, :id).map{ |x| ["#{x.name}", x.id]},
              selected: @artists.try(:id),
              ),
            class: 'selectContainer') 
          %>
        </div>
        <div class="form-group">
          <%= f.label :album_id %><br>
          <%= f.select(:album_id, 
            options_for_select(
              @albums.select(:name, :id).map{ |x| ["#{x.name}", x.id]},
              selected: @albums.try(:id),
              ),
            class: 'selectContainer') 
          %>
        </div>
        <div class="form-group">
          <%= f.label :gender_id %><br>
          <%= f.select(:gender_id, 
            options_for_select(
              @genders.select(:name, :id).map{ |x| ["#{x.name}", x.id]},
              selected: @genders.try(:id),
              ),
            class: 'form-control') 
          %>
        </div>
        <div class="form-group">
          <%= f.label :duration %><br>
          <%= f.number_field :duration, class:"form-control", :required => true %>
        </div>
        <div class="form-group">
          <%= f.label :punctuation %><br>
          <%= f.number_field :punctuation, class:"form-control", :required => true %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
    <% end %>
  </div>
</body>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .button {
    display: inline-block;
    border-radius: 4px;
    background-color: #3ADF00;
    border: none;
    color: #FFFFFF;
    text-align: center;
    font-size: 28px;
    padding: 10px;
    width: 200px;
    transition: all 0.5s;
    cursor: pointer;
    margin: 5px;
  }

  .button span {
    cursor: pointer;
    display: inline-block;
    position: relative;
    transition: 0.5s;
  }

  .button span:after {
    content: '\00bb';
    position: absolute;
    opacity: 0;
    top: 0;
    right: -20px;
    transition: 0.5s;
  }

  .button:hover span {
    padding-right: 25px;
  }

  .button:hover span:after {
    opacity: 1;
    right: 0;
  }
  </style>
</head>
<body>
<div class="container" style="margin-left:20em;">
  <div class="row">
    <div class="col-md-10">
      <h1 class="my-4"><i class="fa fa-music"></i>  Canciones</h1>
    </div>
    <div class="col-md-2">
      <%= link_to new_song_path, class: 'button btn-success btn-xs', title: 'New Artist' do %>
        <span class="fa fa-plus">  Agregar</span>
      <% end %>
    </div>
  </div>

  <% @songs.each do |song| %>
    <div class="row">
      <div class="col-md-2">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src=<%=@albums.find_by_id(song.album_id).image.url(:medium) %> alt="">
        </a>
      </div>
      <div class="col-md-4">
        <h2><%= song.name %></h2>
        <h5><%= @artists.find_by_id(song.artist_id).name %></h5>
      </div>
      <div class="col-md-6">
        <div class="col-md-1">
          <%= link_to new_song_user_path({:user_id => current_user.id, :song_id => song.id}), class: "btn btn-success" do %>
            <span class="fa fa-plus"></span>
          <% end %>
        </div>
        <div class="col-md-1">
          <%= link_to song, class: 'btn btn-info', title: 'Show' do %>
            <span class="fa fa-play"></span>
          <% end %>
        </div>
        <% if current_user.admin? %>
          <div class="col-md-1">
            <%= link_to edit_song_path(song), class: 'btn btn-warning', title: 'Edit' do %>
              <span class="fa fa-pencil"></span>
            <% end %>
          </div>
          <div class="col-md-1">
            <%= link_to song, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', title: 'Destroy' do %>
              <span class="fa fa-trash"></span>
            <% end %>
          </div>
        <% end %>
        <div class="col-md-1">
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle fa fa-list" type="button" data-toggle="dropdown">
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <% @playlists_user.each do |playlist| %>
                <% @my_playlist = @playlists.find_by_id(playlist.playlist_id) %>
                <li>
                  <%= link_to new_playlist_content_path({:playlist_id => @my_playlist.id, :song_id => song.id}) do %>
                    <span class="fa fa-plus"><%= @my_playlist.name %></span>
                  <% end %>
                </li>
         
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>
</body>
</html>

app/views/songs/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<div class="col-lg-4" style="margin-left:50em;">

  <div class="card mt-4">
    <img class="card-img-top img-fluid" src=<%= @album.image.url(:medium) %> alt="">
    <div class="card-body">
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="70"
        aria-valuemin="0" aria-valuemax="100" style="width:70%">
          <span class="sr-only">70% Complete</span>
        </div>
      </div>
      <h3 class="card-title" align="center" ><%= @song.name %></h3>
      <h4 align="center"><%= @artist.name %> - <%= @album.name %></h4>
      <div class="row" style="margin-left:8em;">
        <h1 class="fa fa-backward fa-4x">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1>
        <h1 class="fa fa-play fa-4x">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1>
        <h1 class="fa fa-forward fa-4x">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1>
      </div>
      <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
      4.0 stars
    </div>
  </div>
</div>