config/routes.rb
Rails.application.routes.draw do

  resources :news
  resources :news
  resources :playlist_users
  get 'friend/index'

  get 'friend/:id' => 'friend#show'

  resources :follows
  get 'usuarios/show'

  get 'usuarios/index'

  resources :playlist_contents
  resources :playlists
  get 'mymusic/show'

  get 'mymusic/index'

  resources :song_users
  get 'searcher/show'

  get 'searcher/index'

  get 'admin/show'

  get 'admin/index'

  resources :genders
  root 'welcome#show'
  get 'welcome/show'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do 
    get 'users/registrations/baneo' => 'users/registrations#baneo', :as => :baneo
    get 'users/registrations/desbaneo' => 'users/registrations#desbaneo', :as => :desbaneo
  end
 
  resources :songs
  resources :albums
  resources :artists

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :songs
	belongs_to :artist
	has_attached_file :image, styles: {medium: "400x300>", thumb: "100x100>" }, default_url: "/images/:style/misiing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs
	has_many :albums
end

app/models/follow.rb
class Follow < ActiveRecord::Base
end

app/models/gender.rb
class Gender < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
end

app/models/playlist_user.rb
class PlaylistUser < ActiveRecord::Base
	has_one :user
	has_one :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
	has_many :artists
	belongs_to :album
	belongs_to :artist
end

app/models/song_user.rb
class SongUser < ActiveRecord::Base
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: [:show, :edit, :update, :destroy]

  # GET /follows
  # GET /follows.json
  def index
    @follows = Follow.all
  end

  # GET /follows/1
  # GET /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
    create
  end

  # GET /follows/1/edit
  def edit
  end

  # POST /follows
  # POST /follows.json
  def create
    @follow = Follow.new(follow_params)

    respond_to do |format|
      if @follow.save
        format.html { redirect_to "/friend/index"}
        format.json { render :show, status: :created, location: @follow }
      else
        format.html { render :new }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follows/1
  # PATCH/PUT /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to @follow}
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.json
  def destroy
    @follow.destroy
    respond_to do |format|
      format.html { redirect_to follows_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def follow_params
      params.permit(:user_id_1, :user_id_2)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/mymusic_helper.rb
module MymusicHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/searcher_helper.rb
module SearcherHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id_1 %><br>
    <%= f.text_field :user_id_1 %>
  </div>
  <div class="field">
    <%= f.label :user_id_2 %><br>
    <%= f.text_field :user_id_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing Follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Follows</h1>

<table>
  <thead>
    <tr>
      <th>User id 1</th>
      <th>User id 2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= follow.user_id_1 %></td>
        <td><%= follow.user_id_2 %></td>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New Follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User id 1:</strong>
  <%= @follow.user_id_1 %>
</p>

<p>
  <strong>User id 2:</strong>
  <%= @follow.user_id_2 %>
</p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>